const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

test("MEOS login is limited to the configured police and defensie role allowlist", () => {
  const code = fs.readFileSync(path.join(process.cwd(), "overheid-server.js"), "utf8");
  const routesCode = fs.readFileSync(path.join(process.cwd(), "modules", "meos-api-routes.js"), "utf8");
  const meosServerCode = `${code}\n${routesCode}`;
  const meosRoutesBlock = code.slice(code.indexOf("const meosRoleRoutes"), code.indexOf("const INTERNAL_COMPLAINT_RETURN_TO"));
  const callbackBlock = code.slice(code.indexOf('if (url.pathname === "/auth/discord/callback"'));
  const healthRolesBlock = code.slice(code.indexOf("function configuredMeosHealthRoleIds"), code.indexOf("function meosPermissionsForMember"));

  assert.match(meosRoutesBlock, /roleIds: \["1423468016099918024", "1425931664877551708"\]/);
  assert.match(meosRoutesBlock, /roleIds: \["1423471185391255705", "1425715749862772818"\]/);
  assert.doesNotMatch(meosRoutesBlock, /DISCORD_POLITIE_ROLE_ID|DISCORD_DEFENSIE_ROLE_ID|DISCORD_POLITIE_MEOS_ROLE_ID|DISCORD_MEOS_ROLE_ID/);
  assert.match(code, /function routeRoleIds\(route\)/);
  assert.match(code, /function meosOrganizationPriority\(matches = \[\]\)/);
  assert.match(code, /function meosCallbackUrl\(req\)/);
  assert.match(code, /MEOS_DISCORD_REDIRECT_URI/);
  assert.match(meosServerCode, /const redirectUri = meosCallbackUrl\(req\);/);
  assert.match(code, /if \(isMeosHost\(req\)\) \{\s+const returnTo = safeMeosReturnTo/);
  assert.match(callbackBlock, /isMeosLogin \? meosCallbackUrl\(req\) : cookies\.orp_overheid_redirect \|\| callbackUrl\(req\)/);
  assert.match(code, /portalIdentityForDiscordId\(user\?\.id, \{[\s\S]*organizationPriority,[\s\S]*guildMember: member,[\s\S]*linkMissingDiscordId: true/);
  assert.match(code, /portalPersonDisplayName\(person, \{[\s\S]*fallbackNickname: member\?\.nick \|\| identity\?\.nickname \|\| ""/);
  assert.match(code, /hasPortalIdentityDatabase\(\)/);
  assert.match(code, /function allowMeosDemoProfileFallback\(\)/);
  assert.match(code, /MEOS_REQUIRE_PORTAL_IDENTITY/);
  assert.match(code, /function meosPermissionsForMember\(roles, organizations = \[\], userId = ""\)/);
  assert.match(code, /canViewEntries: true/);
  assert.match(code, /canWriteEntries: true/);
  assert.match(code, /canViewAudit: canDeleteEntries/);
  assert.match(code, /canViewAllProcessVerbals: canDeleteEntries/);
  assert.match(code, /canViewAudit: false/);
  assert.match(code, /canViewAllProcessVerbals: false/);
  assert.match(code, /function configuredMeosHealthRoleIds/);
  assert.match(code, /MEOS_HEALTH_ROLE_IDS/);
  assert.match(code, /MEOS_DEFENSIE_HEALTH_ROLE_IDS/);
  assert.match(code, /MEOS_POLITIE_HEALTH_ROLE_IDS/);
  assert.match(code, /canViewDataHealth/);
  assert.match(meosServerCode, /\/api\/meos\/data-health/);
  assert.match(meosServerCode, /permission: "canViewDataHealth"/);
  assert.match(healthRolesBlock, /DISCORD_KADER_ROLE_ID/);
  assert.match(healthRolesBlock, /DISCORD_POLITIE_KORPSLEIDING_ROLE_ID/);
  assert.doesNotMatch(healthRolesBlock, /OVJ/);
  assert.match(code, /MEOS_DEFENSIE_DELETE_ROLE_IDS/);
  assert.match(code, /MEOS_POLITIE_DELETE_ROLE_IDS/);
  assert.match(code, /const defaultMeosDeleteRoleIds = \["1426544463043362937"\]/);
  assert.match(code, /DISCORD_OVJ_ROLE_ID/);
  assert.match(code, /DISCORD_POLITIE_OVJ_ROLE_ID/);
  assert.match(code, /shouldRejectMutation\(req, appBaseUrl\)/);
  assert.match(code, /meosRateLimitAllows/);
  assert.match(code, /function requireMeosCsrf/);
  assert.match(code, /function meosRateLimitIdentity/);
  assert.match(code, /MEOS_MUTATION_USER_RATE_LIMIT_MAX/);
  assert.match(code, /crypto\.timingSafeEqual/);
  assert.match(meosServerCode, /csrfToken: session\?\.csrfToken \|\| ""/);
  assert.match(meosServerCode, /requireMeosCsrf\(req, session\)/);
  assert.match(code, /Geen actief personeelsprofiel gevonden in Defensie of Politie/);
  assert.match(callbackBlock, /matchingRoutesForRoles\(meosRoleRoutes, roles, user\.id\)/);
  assert.match(callbackBlock, /profile\.permissions = meosPermissionsForMember\(roles, profile\.matchedOrganizations \|\| meosOrganizationPriority\(meosMatches\), user\.id\)/);
  assert.match(callbackBlock, /rememberedState\?\.surface === "meos" \|\| isMeosHost\(req\) \|\| returnTo === "\/meos"/);
  assert.doesNotMatch(callbackBlock, /uniqueRoutesByKey\(\[\.\.\.matches, \.\.\.matchingRoutesForRoles\(meosRoleRoutes/);
});
